name = "mark-portfolio"
main = "worker.js"
compatibility_date = "2025-11-06"

workers_dev = true
preview_urls = false

[triggers]
routes = ["markmonmonteros.site/*"]

[build]
command = "pip install -r requirements.txt && python generate_portfolio_page.py"

#   npm install -g wrangler && wrangler deploy --minify --assets=site <-- deploy command just for reference
